### PR TITLE
added failling test for elements with "circular" dependencies

### PR DESCRIPTION
**Pull request by staabm**

### CODE REVIEW

**Comment by staabm** [comment]
@evert any insights why this test is failling?

**Comment by evert** [comment]
> It feels like the value-object feature should automatically pick-up attributes when equal named properties exist on the object (in case they are unique and no equal-named sub-element exist).

That sounds exactly why the test is failing. Automatically mapping attributes to properties is imho not the greatest solution, because we can't easily figure out what to do when we serialize the objects again. I think it's important that the VO stuff can operate bi-directional.

> alternative2: add a notion of "attribute-serializers/deserializers" additionally to our "element" based ones.

The atom package does this:

https://github.com/fruux/sabre-xml-atom/blob/master/lib/Service.php#L40

So yea I don't think it's a bad idea to add it to the standard list of serializers/deserializers. Clearly there's more than one person who needed this.

**Comment by staabm** [comment]
In my use cse I need a mix of what the valueObject serializer provides in combination with the attribute reading atom does

**Comment by evert** [comment]
In that case I would say you are stuck writing custom serializers/deserializers for those cases. I would say that that is by design :)

**Pull request closed without merging**
