### PR TITLE
External object serializers.

### PR DESCRIPTION
**Pull request by evert**
cc: @staabm. What do you think?

### CODE REVIEW

**Comment by staabm** [comment]
Any chanche we can get the classmap beeing used for reading and writing?

**Comment by evert** [comment]
That wouldn't make a lot of sense, because during reading we don't know yet which class needs to be created. All we have is the element name.

**Comment by staabm** [comment]
Oh, obviously you are right ;-)

**Comment by staabm** [comment]
one thing which bugs me...

```php
class ErpOrderService extends Sabre\Xml\Service {
    public $elementMap = array(
        '{http://b2bOrder.complex.de}order_response' => function (Sabre\Xml\Reader $reader) use ($popoDeserializer) {
            return $popoDeserializer($reader, new OrderResponse(), XMLNS_ORDER);
        },
        '{http://b2bOrder.complex.de}order_status' => function (Sabre\Xml\Reader $reader) use ($popoDeserializer) {
        return $popoDeserializer($reader, new OrderStatus(), XMLNS_ORDER);
        },
    );
}
```

is not valid php, as I cannot use closures on the public field here

**Comment by staabm** [comment]
ok, wil change it to 

```php
$erpOrderService = new Sabre\Xml\Service();
$erpOrderService->elementMap = array(
    '{'. XMLNS_ORDER .'}order_response' => function (Sabre\Xml\Reader $reader) use ($popoDeserializer) {
        return $popoDeserializer($reader, new OrderResponse(), XMLNS_ORDER);
    },
    '{'. XMLNS_ORDER .'}order_status' => function (Sabre\Xml\Reader $reader) use ($popoDeserializer) {
        return $popoDeserializer($reader, new OrderStatus(), XMLNS_ORDER);
    },
);
```

like the Reader/Writer examples

**Comment by staabm** [comment]
... progress...

```php
$xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 <order_response xmlns="http://b2bOrder.complex.de">
 <request_id>4711</request_id>
 <order_id>54752</order_id>
    <order_status xmlns="http://b2bOrder.complex.de">
         <status>INITIALIZED</status>
    </order_status>
 <success>true</success>
 </order_response>';

$popoDeserializer = function(Sabre\Xml\Reader $reader, $popo, $namespace)
{
    if ($reader->isEmptyElement) {
        throw new Exception(__CLASS__ . ' does not support empty elements');
    }

    $reader->read();
    do {

        if ($reader->nodeType === Sabre\Xml\Reader::ELEMENT && $reader->namespaceURI == $namespace) {

            $popo->{$reader->localName} = $reader->parseCurrentElement()['value'];
        } else {
            $reader->read();
        }
    } while ($reader->nodeType !== Sabre\Xml\Reader::END_ELEMENT);

    $reader->read();

    return $popo;
};

$popoSerializer = function(Sabre\Xml\Writer $writer, $popo, $namespace)  {
    foreach(get_object_vars($popo) as $key => $val) {
        $writer->writeElement('{'. $namespace .'}' . $key, $val);
    }
};

class OrderResponse
{
    public $request_id;
    public $order_id;
    public $status_status;
    public $success;
}

class OrderStatus
{
    public $status;
}

define("XMLNS_ORDER", "http://b2bOrder.complex.de");

$erpOrderService = new Sabre\Xml\Service();
$erpOrderService->namespaceMap[XMLNS_ORDER] = '';
// how to read xml into objects
$erpOrderService->elementMap = array(
    '{'. XMLNS_ORDER .'}order_response' => function (Sabre\Xml\Reader $reader) use ($popoDeserializer) {
        return $popoDeserializer($reader, new OrderResponse(), XMLNS_ORDER);
    },
    '{'. XMLNS_ORDER .'}order_status' => function (Sabre\Xml\Reader $reader) use ($popoDeserializer) {
        return $popoDeserializer($reader, new OrderStatus(), XMLNS_ORDER);
    },
);
// how to create xml from obejects
$erpOrderService->classMap = array(
    'OrderResponse' => function(Sabre\Xml\Writer $writer, $orderResponse) use ($popoSerializer) {
        /** @var $orderResponse OrderResponse */
        $popoSerializer($writer, $orderResponse, XMLNS_ORDER);
    },
    'OrderStatus' => function(Sabre\Xml\Writer $writer, $orderStatus) use ($popoSerializer) {
        /** @var $orderStatus OrderStatus */
        $popoSerializer($writer, $orderStatus, XMLNS_ORDER);
    }
);

$reader = $erpOrderService->getReader();
$reader->xml($xml);
$orderResp = $reader->parse()['value'];
var_dump($orderResp);
$writer = $erpOrderService->getWriter();
$writer->openMemory();
$writer->setIndent(true); // pretty print for debugging
$writer->write($orderResp);
var_dump($writer->outputMemory());
```

output

```sh
object(OrderResponse)#11 (5) {
  ["request_id"]=>
  string(4) "4711"
  ["order_id"]=>
  string(5) "54752"
  ["status_status"]=>
  NULL
  ["success"]=>
  string(4) "true"
  ["order_status"]=>
  object(OrderStatus)#12 (1) {
    ["status"]=>
    string(11) "INITIALIZED"
  }
}
string(205) "<:request_id xmlns="http://b2bOrder.complex.de">4711</:request_id>
<:order_id>54752</:order_id>
<:status_status/>
<:success>true</:success>
<:order_status>
 <:status>INITIALIZED</:status>
</:order_status>
"
```

except the `:` in the written xml, it looks fine ;)

**Comment by evert** [comment]
> as I cannot use closures on the public field here

Alternatively you could also have set them in the constructor.

> except the : in the written xml, it looks fine ;)

What's with that `:`? That doesn't look right!

> in case of having a external deserializer it would make sense to have the serializer emit the whole element... wdyt? (in case we agree here, I cannot use the service->write as the root element would then be emitted twice

Personally I would not break the rule, but if you think you have good reasons to do so, you should ;)

**Comment by staabm** [comment]
> What's with that :? That doesn't look right!

I dont know why. The above code is runnable, maybe it helps to repro the problem

**Comment by staabm** [comment]
I guess the `:` are caused by the line `$erpOrderService->namespaceMap[XMLNS_ORDER] = '';`.

I do this to not get a namespace (inspired by the docs from http://sabre.io/xml/writing/)

**Comment by evert** [comment]
Can you try `null` instead of `''` ?

**Comment by staabm** [comment]
@evert you are right, we need `null` instead of `''`.

send a PR which fixes the example code.
https://github.com/fruux/sabre.io/pull/61

It also fixes another error with the code.

So after all this we have a working code:

```php
$xml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
 <order_response xmlns="http://b2bOrder.complex.de">
 <request_id>4711</request_id>
 <order_id>54752</order_id>
    <order_status xmlns="http://b2bOrder.complex.de">
         <status>INITIALIZED</status>
    </order_status>
 <success>true</success>
 </order_response>';

$popoDeserializer = function(Sabre\Xml\Reader $reader, $popo, $namespace)
{
    if ($reader->isEmptyElement) {
        throw new Exception(__CLASS__ . ' does not support empty elements');
    }

    $reader->read();
    do {

        if ($reader->nodeType === Sabre\Xml\Reader::ELEMENT && $reader->namespaceURI == $namespace) {

            $popo->{$reader->localName} = $reader->parseCurrentElement()['value'];
        } else {
            $reader->read();
        }
    } while ($reader->nodeType !== Sabre\Xml\Reader::END_ELEMENT);

    $reader->read();

    return $popo;
};

$popoSerializer = function(Sabre\Xml\Writer $writer, $popo, $namespace)  {
    foreach(get_object_vars($popo) as $key => $val) {
        $writer->writeElement('{'. $namespace .'}' . $key, $val);
    }
};

class OrderResponse
{
    public $request_id;
    public $order_id;
    public $order_status;
    public $success;
}

class OrderStatus
{
    public $status;
}

define("XMLNS_ORDER", "http://b2bOrder.complex.de");

$erpOrderService = new Sabre\Xml\Service();
$erpOrderService->namespaceMap[XMLNS_ORDER] = null;
// how to read xml into objects
$erpOrderService->elementMap = array(
    '{'. XMLNS_ORDER .'}order_response' => function (Sabre\Xml\Reader $reader) use ($popoDeserializer) {
        return $popoDeserializer($reader, new OrderResponse(), XMLNS_ORDER);
    },
    '{'. XMLNS_ORDER .'}order_status' => function (Sabre\Xml\Reader $reader) use ($popoDeserializer) {
        return $popoDeserializer($reader, new OrderStatus(), XMLNS_ORDER);
    },
);
// how to create xml from obejects
$erpOrderService->classMap = array(
    'OrderResponse' => function(Sabre\Xml\Writer $writer, $orderResponse) use ($popoSerializer) {
        /** @var $orderResponse OrderResponse */
        $popoSerializer($writer, $orderResponse, XMLNS_ORDER);
    },
    'OrderStatus' => function(Sabre\Xml\Writer $writer, $orderStatus) use ($popoSerializer) {
        /** @var $orderStatus OrderStatus */
        $popoSerializer($writer, $orderStatus, XMLNS_ORDER);
    }
);

echo "<xmp>";
var_dump($xml);
$orderResp = $erpOrderService->parse($xml);
var_dump($orderResp);
var_dump($erpOrderService->write(get_class($orderResp), $orderResp));
```

do you think this kind of popo serializer/deserializer is something which should be shipped with sabre/xml or is it to specific for my current app?

**Comment by evert** [comment]
I would definitely think it's a good idea to have this as a core feature btw!

**Comment by evert** [comment]
Perhaps we can integrate this in the `Service` class with a function that takes a class name and xml element name and automatically registers both the serializer and deserializer.

**Comment by staabm** [comment]
Agree that having it in the Service class is a good idea. Its the place where this kind of api-sugar should happen. PR incoming

**Pull request merged**
